// Code generated by go-bindata.
// sources:
// data/template_bash
// data/template_bat
// data/template_js
// DO NOT EDIT!

package main

import (
	"fmt"
	"reflect"
	"strings"
	"unsafe"
	"os"
	"time"
	"io/ioutil"
	"path/filepath"
)

func bindataRead(data, name string) ([]byte, error) {
	var empty [0]byte
	sx := (*reflect.StringHeader)(unsafe.Pointer(&data))
	b := empty[:]
	bx := (*reflect.SliceHeader)(unsafe.Pointer(&b))
	bx.Data = sx.Data
	bx.Len = len(data)
	bx.Cap = bx.Len
	return b, nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name string
	size int64
	mode os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dataTemplate_bash = "\x23\x21\x2f\x62\x69\x6e\x2f\x62\x61\x73\x68\x0a\x6d\x6f\x6e\x67\x6f\x20\x24\x4d\x4f\x4e\x47\x4f\x5f\x53\x45\x52\x56\x45\x52\x2f\x7b\x7b\x2e\x44\x62\x4e\x61\x6d\x65\x7d\x7d\x20\x7b\x7b\x2e\x46\x69\x6c\x65\x6e\x61\x6d\x65\x7d\x7d\x5f\x63\x6c\x65\x61\x6e\x2e\x6a\x73\x0a\x69\x66\x20\x5b\x20\x22\x24\x31\x22\x20\x3d\x20\x22\x63\x6c\x65\x61\x6e\x22\x20\x5d\x0a\x74\x68\x65\x6e\x0a\x20\x20\x20\x20\x20\x65\x63\x68\x6f\x20\x22\x4f\x6e\x6c\x79\x20\x63\x6c\x65\x61\x6e\x69\x6e\x67\x20\x72\x65\x71\x75\x65\x73\x74\x65\x64\x22\x0a\x20\x20\x20\x20\x20\x65\x78\x69\x74\x0a\x66\x69\x0a\x0a\x7b\x7b\x72\x61\x6e\x67\x65\x20\x24\x63\x68\x61\x6e\x67\x65\x20\x3a\x3d\x20\x2e\x43\x6f\x6c\x6c\x65\x63\x74\x69\x6f\x6e\x43\x68\x61\x6e\x67\x65\x73\x7d\x7d\x0a\x6d\x6f\x6e\x67\x6f\x69\x6d\x70\x6f\x72\x74\x20\x2d\x2d\x68\x6f\x73\x74\x20\x24\x4d\x4f\x4e\x47\x4f\x5f\x53\x45\x52\x56\x45\x52\x20\x2d\x2d\x64\x62\x20\x7b\x7b\x24\x2e\x44\x62\x4e\x61\x6d\x65\x7d\x7d\x20\x2d\x2d\x63\x6f\x6c\x6c\x65\x63\x74\x69\x6f\x6e\x20\x7b\x7b\x24\x63\x68\x61\x6e\x67\x65\x2e\x43\x6f\x6c\x6c\x65\x63\x74\x69\x6f\x6e\x4e\x61\x6d\x65\x7d\x7d\x20\x3c\x20\x7b\x7b\x24\x63\x68\x61\x6e\x67\x65\x2e\x49\x6d\x70\x6f\x72\x74\x53\x63\x72\x69\x70\x74\x4e\x61\x6d\x65\x7d\x7d\x0a\x7b\x7b\x65\x6e\x64\x7d\x7d\x0a"

func dataTemplate_bashBytes() ([]byte, error) {
	return bindataRead(
		_dataTemplate_bash,
		"data/template_bash",
	)
}

func dataTemplate_bash() (*asset, error) {
	bytes, err := dataTemplate_bashBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/template_bash", size: 314, mode: os.FileMode(420), modTime: time.Unix(1446759934, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _dataTemplate_bat = "\x40\x65\x63\x68\x6f\x20\x6f\x66\x66\x0a\x0a\x6d\x6f\x6e\x67\x6f\x20\x25\x4d\x4f\x4e\x47\x4f\x5f\x53\x45\x52\x56\x45\x52\x25\x2f\x7b\x7b\x2e\x44\x62\x4e\x61\x6d\x65\x7d\x7d\x20\x7b\x7b\x2e\x46\x69\x6c\x65\x6e\x61\x6d\x65\x7d\x7d\x5f\x63\x6c\x65\x61\x6e\x2e\x6a\x73\x0a\x49\x46\x20\x22\x25\x31\x22\x20\x3d\x3d\x20\x22\x63\x6c\x65\x61\x6e\x22\x20\x45\x58\x49\x54\x20\x2f\x42\x20\x30\x0a\x0a\x7b\x7b\x72\x61\x6e\x67\x65\x20\x24\x63\x68\x61\x6e\x67\x65\x20\x3a\x3d\x20\x2e\x43\x6f\x6c\x6c\x65\x63\x74\x69\x6f\x6e\x43\x68\x61\x6e\x67\x65\x73\x7d\x7d\x0a\x6d\x6f\x6e\x67\x6f\x69\x6d\x70\x6f\x72\x74\x20\x2d\x2d\x68\x6f\x73\x74\x20\x25\x4d\x4f\x4e\x47\x4f\x5f\x53\x45\x52\x56\x45\x52\x25\x20\x2d\x2d\x64\x62\x20\x7b\x7b\x24\x2e\x44\x62\x4e\x61\x6d\x65\x7d\x7d\x20\x2d\x2d\x63\x6f\x6c\x6c\x65\x63\x74\x69\x6f\x6e\x20\x7b\x7b\x24\x63\x68\x61\x6e\x67\x65\x2e\x43\x6f\x6c\x6c\x65\x63\x74\x69\x6f\x6e\x4e\x61\x6d\x65\x7d\x7d\x20\x3c\x20\x7b\x7b\x24\x63\x68\x61\x6e\x67\x65\x2e\x49\x6d\x70\x6f\x72\x74\x53\x63\x72\x69\x70\x74\x4e\x61\x6d\x65\x7d\x7d\x0a\x7b\x7b\x65\x6e\x64\x7d\x7d\x0a"

func dataTemplate_batBytes() ([]byte, error) {
	return bindataRead(
		_dataTemplate_bat,
		"data/template_bat",
	)
}

func dataTemplate_bat() (*asset, error) {
	bytes, err := dataTemplate_batBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/template_bat", size: 268, mode: os.FileMode(420), modTime: time.Unix(1446759952, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _dataTemplate_js = "\x7b\x7b\x72\x61\x6e\x67\x65\x20\x24\x63\x68\x61\x6e\x67\x65\x20\x3a\x3d\x20\x2e\x43\x6f\x6c\x6c\x65\x63\x74\x69\x6f\x6e\x43\x68\x61\x6e\x67\x65\x73\x7d\x7d\x0a\x7b\x7b\x72\x61\x6e\x67\x65\x20\x24\x61\x64\x64\x65\x64\x49\x64\x20\x3a\x3d\x20\x24\x63\x68\x61\x6e\x67\x65\x2e\x41\x64\x64\x65\x64\x49\x64\x73\x7d\x7d\x0a\x64\x62\x2e\x7b\x7b\x24\x63\x68\x61\x6e\x67\x65\x2e\x43\x6f\x6c\x6c\x65\x63\x74\x69\x6f\x6e\x4e\x61\x6d\x65\x7d\x7d\x2e\x72\x65\x6d\x6f\x76\x65\x28\x7b\x22\x5f\x69\x64\x22\x3a\x4f\x62\x6a\x65\x63\x74\x49\x64\x28\x22\x7b\x7b\x24\x61\x64\x64\x65\x64\x49\x64\x7d\x7d\x22\x29\x7d\x29\x3b\x0a\x7b\x7b\x65\x6e\x64\x7d\x7d\x0a\x7b\x7b\x65\x6e\x64\x7d\x7d\x0a"

func dataTemplate_jsBytes() ([]byte, error) {
	return bindataRead(
		_dataTemplate_js,
		"data/template_js",
	)
}

func dataTemplate_js() (*asset, error) {
	bytes, err := dataTemplate_jsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/template_js", size: 167, mode: os.FileMode(420), modTime: time.Unix(1446760640, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/template_bash": dataTemplate_bash,
	"data/template_bat": dataTemplate_bat,
	"data/template_js": dataTemplate_js,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"template_bash": &bintree{dataTemplate_bash, map[string]*bintree{
		}},
		"template_bat": &bintree{dataTemplate_bat, map[string]*bintree{
		}},
		"template_js": &bintree{dataTemplate_js, map[string]*bintree{
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, filepath.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

