#!/bin/bash

if [[ $# -gt 0 ]]; then
   MONGO_SERVER="$1"
fi

if [ -z "$MONGO_SERVER" ]; then
    echo "No Mongo server defined, either give server as parameter to this script or set \$MONGO_SERVER environment variable" >&2
    exit 1
fi

echo "Cleaning mongodiff-induced changes from $MONGO_SERVER"
mongo $MONGO_SERVER/{{.DbName}} {{.Filename}}_clean.js
echo "Replaying diff"
{{range $change := .CollectionChanges}}
echo "    Replaying changes done in {{$change.CollectionName}}"
mongoimport --host $MONGO_SERVER --db {{$.DbName}} --collection {{$change.CollectionName}} < {{$change.ImportScriptName}}
{{end}}
