#!/bin/bash
mongo $MONGO_SERVER/{{.DbName}} {{.Filename}}_clean.js
if [ "$1" = "clean" ]
then
     echo "Only cleaning requested"
     exit
fi

{{range $change := .CollectionChanges}}
mongoimport --host $MONGO_SERVER --db {{$.DbName}} --collection {{$change.CollectionName}} < {{$change.ImportScriptName}}
{{end}}
